using System;
using System.Collections.Generic;

namespace Inspur.Billing.Model.Service.Sign
{
    public class SignRequest
    {
        /// <summary>
        /// Current Local Date and Time in ISO 8601 format
        /// </summary>
        public string DateAndTimeOfIssue { get; set; }
        /// <summary>
        /// Invoice Type Normal=0, ProForma=1, Copy=2, Training=3
        /// </summary>
        public string IT { get; set; }
        /// <summary>
        /// Transaction Type Invoice=0, Refund=1
        /// </summary>
        public string TT { get; set; }
        /// <summary>
        /// Other=0, Cash=1, Card=2, Check=3, WireTransfer=4, Voucher=5, MobileMoney=6 
        /// </summary>
        public string PaymentType { get; set; }
        /// <summary>
        /// Optional, Unicode, Max Length 50 characters
        /// </summary>
        public string Cashier { get; set; }
        /// <summary>
        /// Taxpayer ID of the buyer. It is used for B2B and B2G transactions. Optional, ASCII, Max Length 20 characters
        /// </summary>
        public string BD { get; set; }
        /// <summary>
        /// Cost Center ID provided by buyer to the cashier in case Buyer company wants to track spending on a Taxpayer Portal. This shall be taken under consideration only if BD is present on the invoice Optional, Unicode, Max Length 15 characters
        /// </summary>
        public string BuyerCostCenterId { get; set; }
        /// <summary>
        /// Invoice number generated by a POS.
        /// </summary>
        public string InvoiceNumber { get; set; }
        /// <summary>
        /// Required only in case the Invoice Type is Refund or Copy.
        /// In both cases, this field shall contain Invoice Number of previously published Invoice or Refund in RequestedBy-SignedBy-OrdinalNumber format. 
        /// In other cases (for example Normal Sale invoice is referencing to Proforma Sale Invoice) this field is optional.
        /// </summary>
        public string ReferentDocumentNumber { get; set; }
        /// <summary>
        /// Array of Item entities. Invoice contains at least one Item
        /// </summary>
        public List<SignGoodItem> Items { get; set; }
        /// <summary>
        /// Optional, String name-value collection 
        /// Options defines behavior of E-SDC during invoice fiscalization.
        /// Key: OmitQRCodeGen
        /// Value: "1" to omit QR Code generation by E-SDC, "0" to generate and return QR code. 
        /// Key: OmitTextualRepresentation
        /// Value: "1" to omit generation of textual representation by E-SDC, "0" to generate and return textual representation to POS. 
        /// </summary>
        public Dictionary<string, string> Options { get; set; }
        /// <summary>
        /// Base64 encoded MD5 hash of the request data
        /// </summary>
        public string Hash{ get; set; }
    }
}
